### ISSUE TITLE
Implement the `prophet-ms-model` crate

### ISSUE THREAD

**Issue by nnazo** [cloudhubs/prophet2#4]
Create the `prophet-ms-model` crate for keeping track of the microservice call graph ReSSAs from the `prophet-ressa-run` crate (will be renamed from prophet-ressa-minify). The output context of the ReSSA will be used to create a more structured form of the context of the call graph between the microservices.

For this, we need the contexts returned by the ReSSAs to have a consistent format so they can be converted.

**Comment by MicahSchiewe** [comment]
Whoever takes this on will need to decide what attributes our callbacks store into the ReSSA context for identifying services, and how we convert these returned attributes into an MsModel node/edge graph.
