### ISSUE TITLE
Rewrite the Java microservice for `bounded-context`

### ISSUE THREAD

**Issue by nnazo** [cloudhubs/prophet2#5]
There is lots of code that is Java-specific in the current Java version and we will want to have it depend on a more generic form where it received the entities in a structured format from the Rust crate in a request body to do its NLP work.

**Comment by MicahSchiewe** [comment]
Whoever takes this on will need to decide what attributes our callbacks store into the ReSSA context for identifying entities, and how we convert these returned attributes into a bounded context.

**Comment by MicahSchiewe** [comment]
Posting this so we don't lose it. In our chat history, we have the following as a proposed structure for the context:
```json
{
  "services": [
    {
      "name": "servicename",
      "entities": [
        {
          "name": "Entity1",
          "fields": [
            { "type": "T", "name": "foo", "is_collection": boolean }
          ],
          "type": "MongoDB", // or Hibernate etc
        }
      ],
      "calls": [
        { "name": "service1", "type": "RPC" },
        { "name": "service2", "type": "HTTP", "method": "GET" }
      ],
      "language": "C++"
    }
  ]
}
```
And this as a proposed structure for the request to the Java microservice:
```json
{
    "context": {
        "systemName": "SystemName",
        "modules": [
            {
                "name": "ModuleName",
                "entities": [
                    {
                        "entityName": "EntityName",
                        "fields": [
                            {
                                "name": "attributeName",
                                "type": "attributeType"
                            },
                            ...
                        ]
                    }
                ]
            },
            ...
        ]
    },
    "useWuPalmer": true
}
```

**Comment by MicahSchiewe** [comment]
This is already implemented in the `bounded-context-app` submodule, apparently forgot to close the issue.
